source 'http://rubygems.org'

gem 'rails', '5.2.6.2'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 5.0.5'
  gem 'coffee-rails', '~> 4.2.2'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '>= 4.0.1'

gem 'haml'
gem 'crummy', :path => '../'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

group :test, :development do
  gem "rspec-rails", "~> 2.13", ">= 2.13.0"
end
